/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Carier.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Carier.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[0, 0.002, 0]} rotation={[0, -0.419, 0]} scale={[0.178, 0.163, 0.409]} />
    </group>
  )
}

useGLTF.preload('/Carier.gltf')
